// Generated by Wrangler on Sat Aug 03 2024 17:34:42 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	PRO: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	DISCORD_BOT_TOKEN: string;
	DISCORD_REDIRECT_URI: string;
	DB: D1Database;
}
